import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import { increment } from "../store/counterSlice";

export default function Home() {
  const dispath = useDispatch();

  const counter = useSelector((state) => state.counter.count);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => dispath(increment())}>Plus</button>
      <p>{counter}</p>

      <Link href="/nxtpage">next page pe jao</Link>
    </div>
  );
}
